# fly.toml app configuration file generated for question-the-docs on 2023-08-18T15:45:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "question-the-docs"
primary_region = "ams"

[build]

[processes]
  worker = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"

[[services]]
  protocol = ""
  internal_port = 8000
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["worker"]

[[statics]]
  guest_path = "/app/build"
  url_prefix = "/"
